### PR TITLE
fix: issue #11, memory cleaning on timers

### LINKED ISSUE #11: improve connection stability
Automerge can take many seconds processing large documents on load, so we want to make sure that only the first connection loads and generates the automerge doc.  Additionally, all the subsequent connections need to wait for that initial connection to finish before continuing to initialize.

We also need to implement a disconnect timer so that things don't get immediately cleaned up when the socket count goes to 0.  If someone is having connection issues, this causes a cycle of building the automerge document and cleaning it up over and over, and could cause a server resource feedback loop

- [x] make sure only the first user starts creating the automerge document (move counter up)
- [x] put subsequent connections in a setTimeout loop waiting on the first connection to build the automerge document

### PR DESCRIPTION
**Pull request by jnbarlow**
resolves #11

### CODE REVIEW

File: packages/backend/src/SocketIOConnection.ts [hunk 1]
```diff
@@ -63,6 +72,13 @@ export default class SocketIOCollaboration {
       options.saveFrequency || 2000
     )
 
+    this.backends = []
+    this.backendCounts = []
+    //spawn cleaner
+    setTimeout(() => {
```
Comment (djmccormick) [inline packages/backend/src/SocketIOConnection.ts:78]: Let's make this a `setInterval` instead of a `setTimeout` so we don't have to call ourselves in `cleaner`.

File: packages/backend/src/SocketIOConnection.ts [hunk 2]
```diff
@@ -92,33 +108,77 @@ export default class SocketIOCollaboration {
...
+          automerge: new AutomergeBackend(),
+          ready: false,
+          failed: false,
+          cleanupTimer:
+            Math.floor(Date.now() / 1000) +
+            (this.options.cleanThreshold || 30) * 60
+        }
 
-        if (!this.backends[path].getDocument(path)) {
+        this.backendCounts[path] = 1
```
Comment (djmccormick) [inline packages/backend/src/SocketIOConnection.ts:127]: Now that we store other metadata in `this.backends`, let's store the `count` on `this.backends`. We can `_.mapKeys(this.backends, backend => backend.count)` to pull the count stats.

File: packages/backend/src/SocketIOConnection.ts [hunk 3]
```diff
@@ -92,33 +108,77 @@ export default class SocketIOCollaboration {
...
-      const path = socket.nsp.name
       const query = socket.handshake.query
       const { onDocumentLoad } = this.options
 
       //make some backends if this is the first time this meeting is loaded.
       if (!this.backends[path]) {
-        this.backends[path] = new AutomergeBackend()
-        this.backendCounts[path] = 0
+        this.backends[path] = {
+          automerge: new AutomergeBackend(),
```
Comment (djmccormick) [inline packages/backend/src/SocketIOConnection.ts:119]: Let's get rid of `ready` and `failed` and use a Promise instead. I can help with this logic when you get there, gimme a ping.

**Review by djmccormick — CHANGES_REQUESTED** [review]
We also discussed setting cleanupTimer on disconnect instead of on every op.

**Review by djmccormick — APPROVED** [review]
